### ISSUE TITLE
Unable to install Smarties.IO over raspbian stretch.

### ISSUE THREAD

**Issue by asconint2019** [WoodySlum/smarties.io#1]
Hi Woody,
          i am unable to to install smarties.io on raspbian stretch i also tried  latest raspbian buster but it doesn't work. i have pasted the issue which i am getting upon instalation,thanks.

---------------------------------------------------------------
The following packages have unmet dependencies:
 smarties : Depends: gstreamer-1.0 but it is not installable
E: Unable to correct problems, you have held broken packages.
---------------------------------------------------------------

**Comment by WoodySlum** [comment]
Hi @asconint2019  thanks for reporting ! That's correct it's a mistake dependency gstreamer-1.0 is not correctly named on raspberry. I'm going to fix this quickly.

**Comment by WoodySlum** [comment]
Hey, could you just try this  and tell me if it's now working better ? 

```
apt-get update
apt-get install -y smarties
```

**Comment by asconint2019** [comment]
Hi Woody,
             Thanks for your reply, Let me try it and will update you accordingly,Thanks again.

Regards,
Bilal

**Comment by asconint2019** [comment]
Hi Woody,
             It‘s up and running now. Thanks.
Regards,
 Bilal

**Comment by WoodySlum** [comment]
Glad to hear !
